version: "3"

networks:
  laravel:
    ipam:
      driver: default
      config:
        - subnet: 173.28.0.0/16

services:
  laravel_nginx:
    image: nginx:stable-alpine
    container_name: laravel_nginx
    ports:
      - "8100:80"
    working_dir: /var/www/html/blog
    volumes:
      - ./src:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel_php
      - laravel_postgres
    networks:
      - laravel
#        ipv4_address: 173.28.1.1

  laravel_postgres:
    image: postgres:11-alpine
    container_name: laravel-postgres
    volumes:
      - "./sourcefiles/postgres:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=rootsecret
      - POSTGRES_DB=laraveldb
    ports:
      - "5432:5432"
    networks:
      - laravel
#        ipv4_address: 173.28.1.2

  laravel_php:
    volumes:
#      - ./src:/var/www
      - ./src/html/blog:/var/www/blog
      - ./.docker/conf/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./.docker/conf/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    working_dir: /var/www/blog
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_php
    ports:
      - "9000:9000"
    networks:
      - laravel
#        ipv4_address: 173.28.1.3

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "example@email.com"
      PGADMIN_DEFAULT_PASSWORD: "PgAdmin2019!"
    ports:
      - 8080:80
