version: "3"

networks:
  laravel:

services:
  laravel_nginx:
    image: nginx:stable-alpine
    container_name: laravel_nginx
    ports:
      - "8100:80"
    volumes:
      - ./src:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel_php
      - laravel_mysql
    networks:
      - laravel

  laravel_mysql:
    image: mysql:5.7.22
    container_name: laravel_mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: MYSQL_ROOT_PASSWORD
    networks:
      - laravel

  laravel_php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_php
    volumes:
      - ./src:/var/www
    ports:
      - "9000:9000"
    networks:
      - laravel
